version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/RDMSharp/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "nuget"
    directory: "/RDMSharpTests/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5